# Fetching the latest node image on apline linux
FROM node:22-alpine AS development

# Declaring env
ENV NODE_ENV development

# Setting up the work directory
WORKDIR /profile_builder
# Installing dependencies
COPY package*.json ./
COPY .env ./
RUN npm install
RUN npm install

# Copying all the files in our project
COPY . .

EXPOSE 3000

# Starting our application
CMD [ "npm", "start" ]